"""add agent_id to leads

Revision ID: 2bde9b53a921
Revises: 3c13277f1a12
Create Date: 2026-07-17 07:23:00.299711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bde9b53a921'
down_revision: Union[str, Sequence[str], None] = '3c13277f1a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('agent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'agent_id')
    # ### end Alembic commands ###
