"""add beds column to properties

Revision ID: 7d79bae69d90
Revises: e4ebef0a332a
Create Date: 2026-07-16 07:47:20.422335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d79bae69d90'
down_revision: Union[str, Sequence[str], None] = 'e4ebef0a332a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('beds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'beds')
    # ### end Alembic commands ###
