"""improve customer constraints

Revision ID: affeab119ad7
Revises: 3c7bd488b96c
Create Date: 2026-07-19 16:17:22.386079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affeab119ad7'
down_revision: Union[str, Sequence[str], None] = '3c7bd488b96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
